# Generated by Django 4.1.7 on 2023-03-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ('time_update', 'title'), 'verbose_name_plural': 'Известные женщины'},
        ),
    ]
