# Generated by Django 4.1.7 on 2023-03-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
