# Generated by Django 4.1.7 on 2023-03-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_comments_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
